### PR TITLE
LPS-89146 launch tests with suites

### PR DESCRIPTION
**Pull request by javiergamarra**
Hi!

As we discussed, I got the Ok of daldi and adolfo to launch delivery tests in their suites. This packages are Ok for now.

### CODE REVIEW

**Comment by jpince** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jpince** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/71996. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jpince** [comment]
@nhpatt checked with CI Infrastructure team, this should indeed only run the headless-delivery tests. Please feel free to send directly to BChan in the future, I don't need to review any code. I'm just here to help :). Please let us know if something doesn't work as expected. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by javiergamarra** [comment]
Thanks! :D

**Pull request closed without merging**
