### PR TITLE
TEST LPS-98200

### PR DESCRIPTION
**Pull request by jpince**
https://issues.liferay.com/browse/LPS-98200

### CODE REVIEW

**Comment by jpince** [comment]
ci:test

**Comment by jpince** [comment]
ci:test

**Comment by jpince** [comment]
ci:test

**Comment by jpince** [comment]
@petershin I'm testing moving chat and mail-reader into the deprecated folder. Can you please tell me why ModulesStructureTest is complaining about this? `junit.framework.AssertionFailedError: Forbidden modules/apps/deprecated/chat/build.gradle`
Seems like the other modules in deprecated have a build.gradle file

**Comment by petershin** [comment]
@jpince - It failed because of this line in the Gradle file: `apply plugin: "com.liferay.app.defaults.plugin"`

I don't see an existing pattern that can be copied.  Just offhand, maybe try this and rerun the CI tests:

```
modules/apps/deprecated/chat-api/...
modules/apps/deprecated/chat-service/...
modules/apps/deprecated/chat-test/...
modules/apps/deprecated/chat-web/...
```

**Pull request closed without merging**
