### PR TITLE
lps-86544

### PR DESCRIPTION
**Pull request by lawrence-lee**

### CODE REVIEW

**Comment by lawrence-lee** [comment]
ci:test:relevant

**Comment by jpince** [comment]
@lawrence-lee batch is passing in upstream, so I pushed up a revert, see https://github.com/liferay/liferay-portal/commit/6e7a00c30f0478818b192169389d3e76fffe12d8

**Comment by jpince** [comment]
ci:stop

**Comment by lawrence-lee** [comment]
@jpince thanks!

**Pull request closed without merging**
