### PR TITLE
LPS-83829 Remove lodash usage from frontend-js-web

### PR DESCRIPTION
**Pull request by julien**

### CODE REVIEW

**Comment by julien** [comment]
ci:test

**Comment by julien** [comment]
Hi @jpince,

Since this commit has been reverted, could you please check this pull request.

Thanks!

**Comment by jpince** [comment]
Forwarded to https://github.com/john-co/liferay-portal/pull/29 for testing. Unfortunately, we don't have IE on the PR Tester :/

**Comment by jpince** [comment]
@julien see SF error in https://github.com/john-co/liferay-portal/pull/29#issuecomment-436683301. Please resend to @john-co

**Comment by julien** [comment]
@jpince ok thanks again for the help

**Pull request closed without merging**
