### PR TITLE
LPS-69953

### PR DESCRIPTION
**Pull request by giros**
https://issues.liferay.com/browse/LPS-69953

cc @matethurzo

### CODE REVIEW

**Comment by giros** [comment]
ci:test

**Comment by jpince** [comment]
@giros is there a reason you're sending this to me? I don't mind helping, I'm just curious as to the reason :)

**Comment by jpince** [comment]
@giros I just saw your comment on the other pull. You might as well send this directly to Brian, since CI is down right now (so I wouldn't be able to view test results for several hours, between the time it takes to fix the CI issue and retest)

**Comment by giros** [comment]
@jpince I sent this to you as you pointed out the test failures on https://github.com/brianchandotcom/liferay-portal/pull/62170
I sent this to Brian as per your suggestion: https://github.com/brianchandotcom/liferay-portal/pull/62387

**Pull request closed without merging**
