### PR TITLE
Revert "LPS-77168 Add columns to DDMFormInstanceVersion and DDMStructureVersion to be able to use staging"

### PR DESCRIPTION
**Pull request by matethurzo**
@jpince this is solving the current CI issues on master, can you please push it right away?

@rafaprax @inacionery the changes for LPS-77168 broke staging but also a few DDM related tests: https://github.com/brianchandotcom/liferay-portal/pull/55001

I've rolled them back and the tests are green again, can you please check why are they breaking?

cc @brianchandotcom @mhan810

### CODE REVIEW

**Comment by matethurzo** [comment]
ci:test

**Comment by jpince** [comment]
@matethurzo sorry I'm on vacation, I asked @brianchiu to take a look

**Comment by brianchiu** [comment]
@matethurzo @jpince 
I just checked and @rafaprax also sent a pull with the same revert. BChan has already merged it. See https://github.com/brianchandotcom/liferay-portal/pull/55018

cc @brianchandotcom

**Comment by jpince** [comment]
ci:close

**Pull request closed without merging**
