### PR TITLE
LPS-118750 Remove portal accounts from 7.3 CE and DXP bundles

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-118750](https://issues.liferay.com/browse/LPS-118750).

### CODE REVIEW

**Comment by jpince** [comment]
ci:test:sf

**Comment by jpince** [comment]
Just started reviewing :)

**Comment by jpince** [comment]
@drewbrokke I was able to reproduce the issue locally via `ant format-source-current-branch`. SF passed, with only this in the log:
```
     [java] /media/jpince/l/m/modules/apps/account/app.bnd (SourceCheck:BNDSuiteCheck)
```

However, SF did make a change. I think `ci:test:sf` also runs git diff, which is why it failed in the PR but not locally. This is what came up after I tried `git add -u`:
```
diff --git a/modules/apps/account/app.bnd b/modules/apps/account/app.bnd
index 79ea173bc762..16de77ba87ac 100644
--- a/modules/apps/account/app.bnd
+++ b/modules/apps/account/app.bnd
@@ -1,6 +1,6 @@
 Liferay-Releng-App-Description:
 Liferay-Releng-App-Title: ${liferay.releng.app.title.prefix} Account
-Liferay-Releng-Bundle: false
+Liferay-Releng-Bundle: true
 Liferay-Releng-Category: Utility
 Liferay-Releng-Demo-Url:
 Liferay-Releng-Deprecated: false
```
I realized we designed SF for the more common case, where the developer is turning the app ON. Check out modules/apps/bookmarks/app.bnd for an example where Bundle: false. You may just need to iterate until SF doesn't try to make any more changes.

Send it back to me (or just ping me) if you need some help, otherwise it can go straight to BChan.

**Comment by jpince** [comment]
@drewbrokke I think you need to set
```
Fix-Delivery-Method: 
...
Liferay-Releng-Portal-Required: false
...
Liferay-Releng-Suite:
```

**Comment by drewbrokke** [comment]
@jpince looks like if you set `Liferay-Releng-Suite` to blank, SF will fix the other two you mentioned.

**Pull request closed without merging**
