### PR TITLE
LRQA-46551 | master

### PR DESCRIPTION
**Pull request by john-co**
https://issues.liferay.com/browse/LRQA-46551

### CODE REVIEW

**Comment by john-co** [comment]
@brunobasto, @xbrianlee, please turn back on your respective js tests when fix is ready. Thank you.

cc/ @jbalsas, @vicnate5

**Comment by jpince** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jpince** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/67500. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jpince** [comment]
@john-co please send straight to BChan next time, I don't need to review

**Pull request closed without merging**
