### PR TITLE
LPS-105290 Baseline (auto-generated)

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test:stable

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jpince** [comment]
Just started reviewing :)

**Comment by jpince** [comment]
Thanks @jbalsas, pushed to Brian Chan's origin https://github.com/brianchandotcom/liferay-portal/commit/d32433634de29c1e6a38dd215b698a804434dea0

**Pull request closed without merging**
