### PR TITLE
LPS-117854 | master

### PR DESCRIPTION
**Pull request by jpince**
The source code will be removed in a later pull request, see [LPS-117855](https://issues.liferay.com/browse/LPS-117855) / [LPS-117856](https://issues.liferay.com/browse/LPS-117856)

Ticket for this pull request: https://issues.liferay.com/browse/LPS-117854

cc/ @arboliveira @xbrianlee

### CODE REVIEW

**Comment by jpince** [comment]
ci:forward

**Comment by joshchong** [comment]
ci:stop

**Comment by joshchong** [comment]
@jpince we actually still need `portal-search-elasticsearch6-xpack-monitoring` since that app is meant to be released and work with elasticsearch 7 (despite its name). I'm not sure if we have plans to create a separate elasticsearch7 xpack monitoring app since the code would be the same. @arboliveira can you confirm?

**Comment by jpince** [comment]
continued in https://github.com/jpince/liferay-portal/pull/146

**Pull request closed without merging**
