### PR TITLE
LRQA-58726 | master

### PR DESCRIPTION
**Pull request by jpince**
https://issues.liferay.com/browse/LRQA-58726

Also reverts bb9c145059ef343d2d1137062b1bcf2adb183a13, since it was a temporary commit needed to build the 7.3 CE GA3 release api jar.

### CODE REVIEW

**Comment by jpince** [comment]
ci:test:sf

**Comment by jpince** [comment]
Reverts commit from https://github.com/brianchandotcom/liferay-portal/pull/89059

**Comment by jpince** [comment]
ci:test:relevant

**Comment by jpince** [comment]
@petershin does this seem right to you? I don't remember doing this before (maybe because I blindly pushed it to BChan without testing?)
```
     [echo]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [echo] = ================================================== ========== ========== ========== ========== ==========
     [echo] * com.liferay.portal.kernel.util                     MINOR      10.4.0     10.4.0     10.5.0     VERSION INCREASE REQUIRED
     [echo] 	<   class      com.liferay.portal.kernel.util.ReleaseInfo
     [echo] 		+   field      RELEASE_7_3_3_BUILD_NUMBER
     [echo] 			+   access     final
     [echo] 			+   access     static
     [echo] 			+   constant   7303
     [echo] 			+   return     int
     [echo] [Baseline Warning] Bundle Version Change Recommended: 7.4.0
```

**Comment by jpince** [comment]
ci:forward

**Comment by brianchandotcom** [comment]
I merged this manually because it was referenced in https://github.com/brianchandotcom/liferay-portal-ee/pull/30529

**Pull request closed without merging**
