### PR TITLE
LPS-83072 Layout prototype pages group is not staged

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:test

**Comment by pavel-savinov** [comment]
Hi Jason, this is the fix for the issue you sent me by email. Thanks!

@matethurzo FYI.

**Comment by jpince** [comment]
'Pull <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jpince** [comment]
@pavel-savinov thanks! Forwarded to Brian https://github.com/brianchandotcom/liferay-portal/pull/61682

**Pull request closed without merging**
