### PR TITLE
RELEASE-4273 Update release.properties and ReleaseInfo.java

### PR DESCRIPTION
**Pull request by sophia6497**
Hi @jpince, 

   PR to you since ci test is not working on Rafaela's repo. Thank you.

### CODE REVIEW

**Comment by sophia6497** [comment]
ci:test:sf

**Comment by sophia6497** [comment]
ci:test:smoke

**Comment by rafaela-nasciment0** [comment]
Hi @sophia6497 , thanks for making these changes. 
I reviewed and looks good. I'll forward it to Brian.

**Comment by rafaela-nasciment0** [comment]
ci:forward

**Comment by jpince** [comment]
Closing, see Slack

**Pull request closed without merging**
