### PR TITLE
LPS-125625 | master

### PR DESCRIPTION
**Pull request by jpince**
https://issues.liferay.com/browse/LPS-125625

### CODE REVIEW

**Comment by jpince** [comment]
ci:test:sf

**Comment by jpince** [comment]
ci:test:relevant

**Comment by jpince** [comment]
ci:test:sf

**Comment by jpince** [comment]
ci:test:acceptance-ce

**Comment by jpince** [comment]
ci:test:acceptance

**Comment by jpince** [comment]
ci:forward

**Comment by jpince** [comment]
@petershin can you please review? Just changing `.lfrbuild-portal` files in archived folder to `.lfrbuild-portal-deprecated`. I couldn't see any reason why we would need these modules in the build. I'm already running `ci:forward`, but thought I should ask your opinion in case you know something I don't. :smile: Thank you!

**Comment by petershin** [comment]
@jpince - Took a quick look and it looks ok to me.

**Comment by jpince** [comment]
ci:forward

**Comment by jpince** [comment]
ci:forward

**Pull request closed without merging**
