### PR TITLE
LPS-80777 Correct upgrade process

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test

**Comment by jkappler** [comment]
@jpince, just checking if it's the upgrade process the one responsible for the issue with lpkg

**Comment by jpince** [comment]
ci:test:relevant

**Comment by jpince** [comment]
@jkappler looks good, the lpkg batches passed. Will forward this in a bit.

**Comment by jkappler** [comment]
Thanks @jpince!

**Comment by jpince** [comment]
'Pull <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jpince** [comment]
Forwarded to BChan: https://github.com/brianchandotcom/liferay-portal/pull/58764

**Pull request closed without merging**
