### PR TITLE
LPS-140106 | master

### PR DESCRIPTION
**Pull request by jpince**
https://issues.liferay.com/browse/LPS-140106

### CODE REVIEW

**Comment by jpince** [comment]
ci:test:sf

**Comment by jpince** [comment]
ci:test:lpkg

**Comment by jpince** [comment]
ci:test:relevant (lpkg test failures unrelated to moving SAML app to a core app :heavy_check_mark: )

**Comment by stian-sigvartsen** [comment]
@jpince I've had a look at the changes, more for learning than reviewing. Please forward to Brian if you are happy 👍

**Comment by jpince** [comment]
Forwarded to Brian manually: https://github.com/brianchandotcom/liferay-portal/pull/108127

**Pull request closed without merging**
