### PR TITLE
LPS-128204

### PR DESCRIPTION
**Pull request by petershin**

### CODE REVIEW

**Comment by petershin** [comment]
To run: `gw -b releng.gradle prepareMajorIncrementAppProperties`

If an app.property file should be ignored add a `.lfrbuild-app-portal-build-ignore` marker file.  The task already skips marketplace because it doesn't follow the pattern `app.marketplace.version=x.x.x`.

```
app.marketplace.version=10
```

**Comment by petershin** [comment]
ci:test:sf

**Comment by jpince** [comment]
Just started reviewing :)

**Comment by jpince** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/99303.

**Pull request closed without merging**
