### PR TITLE
LPS-76719 | master

### PR DESCRIPTION
**Pull request by jpince**
repeat testing with portal-license-jdk8 only. See https://github.com/brianchandotcom/liferay-portal/pull/53958#issuecomment-354186362

### CODE REVIEW

**Comment by jpince** [comment]
ci:test

**Comment by amosfong** [comment]
@caustin582, I think this might be related to your changes recently?

**Comment by timpak** [comment]
ci:close

**Comment by timpak** [comment]
ci:reopen

**Comment by timpak** [comment]
ci:test:help

**Comment by timpak** [comment]
ci:help

**Pull request closed without merging**
