### PR TITLE
LPS-110426 | master

### PR DESCRIPTION
**Pull request by jpince**
3 `ci:forward` so far

https://issues.liferay.com/browse/LPS-110426

Forwarding for Hugo. Passed testing in #136 only running PMD.

### CODE REVIEW

**Comment by jpince** [comment]
ci:forward

**Comment by jpince** [comment]
ci:forward

**Comment by jpince** [comment]
ci:forward @yichenroy strange issue? see last semantic-versioning batch
https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/313191/consoleText

**Comment by yichenroy** [comment]
@jpince not sure what's going on here, have you seen any other instances of this?
The slave might be having some kind of I/O issue from what it looks like in its build history, we'll investigate.

**Comment by jpince** [comment]
@yichenroy no, I don't think I've seen anything like that. Just concerned it was a bad slave or something more serious :)

**Comment by yichenroy** [comment]
It is most likely a bad slave, we've taken down the slave and are doing some maintenance on it before we bring it back online.

Thanks for reporting!

**Pull request closed without merging**
