### PR TITLE
RELEASE-4273 Update release.properties and ReleaseInfo.java

### PR DESCRIPTION
**Pull request by sophia6497**
Hi @jpince,

    Please review it again. Thank you.

### CODE REVIEW

**Comment by sophia6497** [comment]
ci:test:sf

**Comment by sophia6497** [comment]
ci:test:smoke

**Comment by sophia6497** [comment]
ci:stop

**Comment by sophia6497** [comment]
Closing this PR since I combined 2 prs to one.

**Comment by sophia6497** [comment]
ci:test:sf

**Comment by sophia6497** [comment]
ci:test:smoke

**Comment by rafaela-nasciment0** [comment]
Just starting reviewing :)

**Comment by jpince** [comment]
Rafaela forwarded to Brian.

**Pull request closed without merging**
