### PR TITLE
RELEASE-3029 TEST | master

### PR DESCRIPTION
**Pull request by jpince**
https://issues.liferay.com/browse/RELEASE-3029

### CODE REVIEW

**Comment by jpince** [comment]
ci:test:relevant

**Comment by jpince** [comment]
ci:test:sf

**Comment by jpince** [comment]
ci:test:sf on newest commits. relevant results will be on old commits.

**Comment by jpince** [comment]
@petershin can you please look at https://github.com/jpince/liferay-portal/pull/155/commits/3ddbe59c5492683c4d9ad880bfce07e03a2f9c82? These changes were made by prepareMajorIncrement, but SF complained about them.

**Comment by petershin** [comment]
@jpince - Looks good.  I'd manually revert the ones SF complains about too

**Comment by jpince** [comment]
@petershin the commit you reviewed was my manual revert, and SF was satisfied. Should prepareMajorIncrement be adjusted so it doesn't make those changes?

**Comment by jpince** [comment]
Continued here: https://github.com/jpince/liferay-portal/pull/156

**Pull request closed without merging**
